//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itixo.Timesheets.Shared.Resources.AdminClient; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Texts {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Texts() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itixo.Timesheets.Shared.Resources.AdminClient.Texts", typeof(Texts).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nejprve přidejte svůj první účet v sekci .
    /// </summary>
    public static string Account_AddText {
        get {
            return ResourceManager.GetString("Account_AddText", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to a.
    /// </summary>
    public static string And {
        get {
            return ResourceManager.GetString("And", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Smazat.
    /// </summary>
    public static string Delete {
        get {
            return ResourceManager.GetString("Delete", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Upozornění.
    /// </summary>
    public static string Dialog_Warning {
        get {
            return ResourceManager.GetString("Dialog_Warning", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Editovat.
    /// </summary>
    public static string Edit {
        get {
            return ResourceManager.GetString("Edit", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Email.
    /// </summary>
    public static string Email {
        get {
            return ResourceManager.GetString("Email", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to STRÁNKA NENALEZENA.
    /// </summary>
    public static string Error_404_Reason {
        get {
            return ResourceManager.GetString("Error_404_Reason", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 404.
    /// </summary>
    public static string Error_404_Title {
        get {
            return ResourceManager.GetString("Error_404_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to NEOČEKÁVANÁ CHYBA APLIKACE.
    /// </summary>
    public static string Error_500_Reason {
        get {
            return ResourceManager.GetString("Error_500_Reason", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 500.
    /// </summary>
    public static string Error_500_Title {
        get {
            return ResourceManager.GetString("Error_500_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Zpět na hlavní stránku.
    /// </summary>
    public static string Error_GoBack {
        get {
            return ResourceManager.GetString("Error_GoBack", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Účty.
    /// </summary>
    public static string Nav_Dropdown_Account_Accounts {
        get {
            return ResourceManager.GetString("Nav_Dropdown_Account_Accounts", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Odhlásit.
    /// </summary>
    public static string Nav_Dropdown_Account_Logout {
        get {
            return ResourceManager.GetString("Nav_Dropdown_Account_Logout", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nastavení.
    /// </summary>
    public static string Nav_Dropdown_Account_Settings {
        get {
            return ResourceManager.GetString("Nav_Dropdown_Account_Settings", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Synchronizace.
    /// </summary>
    public static string Nav_Dropdown_Synchronization {
        get {
            return ResourceManager.GetString("Nav_Dropdown_Synchronization", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Historie.
    /// </summary>
    public static string Nav_Dropdown_Synchronization_History {
        get {
            return ResourceManager.GetString("Nav_Dropdown_Synchronization_History", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Synchronizátor.
    /// </summary>
    public static string Nav_Dropdown_Synchronization_Synchronizator {
        get {
            return ResourceManager.GetString("Nav_Dropdown_Synchronization_Synchronizator", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznamy.
    /// </summary>
    public static string Nav_Dropdown_TimeEntries {
        get {
            return ResourceManager.GetString("Nav_Dropdown_TimeEntries", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Přidat záznam.
    /// </summary>
    public static string Nav_Dropdown_TimeEntries_Add {
        get {
            return ResourceManager.GetString("Nav_Dropdown_TimeEntries_Add", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Detailní.
    /// </summary>
    public static string Nav_Dropdown_TimeEntries_Detail {
        get {
            return ResourceManager.GetString("Nav_Dropdown_TimeEntries_Detail", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznamy ke smazání.
    /// </summary>
    public static string Nav_Dropdown_TimeEntries_PreDelete {
        get {
            return ResourceManager.GetString("Nav_Dropdown_TimeEntries_PreDelete", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sumarizované.
    /// </summary>
    public static string Nav_Dropdown_TimeEntries_Sum {
        get {
            return ResourceManager.GetString("Nav_Dropdown_TimeEntries_Sum", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Workspaces.
    /// </summary>
    public static string Nav_Workspaces {
        get {
            return ResourceManager.GetString("Nav_Workspaces", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nový.
    /// </summary>
    public static string New {
        get {
            return ResourceManager.GetString("New", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznamy ke smazání.
    /// </summary>
    public static string PreDeleteTitle {
        get {
            return ResourceManager.GetString("PreDeleteTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Filtrace.
    /// </summary>
    public static string Report_Filter_Title {
        get {
            return ResourceManager.GetString("Report_Filter_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Uložit.
    /// </summary>
    public static string Save {
        get {
            return ResourceManager.GetString("Save", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Synchronizovat.
    /// </summary>
    public static string Sync {
        get {
            return ResourceManager.GetString("Sync", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Doba trvání.
    /// </summary>
    public static string Sync_History_Duration {
        get {
            return ResourceManager.GetString("Sync_History_Duration", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sync. záznamy od.
    /// </summary>
    public static string Sync_History_EntriesFrom {
        get {
            return ResourceManager.GetString("Sync_History_EntriesFrom", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sync. záznamy do.
    /// </summary>
    public static string Sync_History_EntriesTo {
        get {
            return ResourceManager.GetString("Sync_History_EntriesTo", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Vloženo schválených.
    /// </summary>
    public static string Sync_History_InsertedApprovedCount {
        get {
            return ResourceManager.GetString("Sync_History_InsertedApprovedCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Vloženo ke schválení.
    /// </summary>
    public static string Sync_History_InsertedDraftedCount {
        get {
            return ResourceManager.GetString("Sync_History_InsertedDraftedCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sync. běžel od.
    /// </summary>
    public static string Sync_History_StartTime {
        get {
            return ResourceManager.GetString("Sync_History_StartTime", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Výsledek.
    /// </summary>
    public static string Sync_History_State {
        get {
            return ResourceManager.GetString("Sync_History_State", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sync. běžel do.
    /// </summary>
    public static string Sync_History_StopTime {
        get {
            return ResourceManager.GetString("Sync_History_StopTime", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Aktualizováno schválených.
    /// </summary>
    public static string Sync_History_UpdatedApprovedCount {
        get {
            return ResourceManager.GetString("Sync_History_UpdatedApprovedCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Aktualizováno ke schválení.
    /// </summary>
    public static string Sync_History_UpdatedDraftedCount {
        get {
            return ResourceManager.GetString("Sync_History_UpdatedDraftedCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Spustil.
    /// </summary>
    public static string Sync_History_Who {
        get {
            return ResourceManager.GetString("Sync_History_Who", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Rozmezí synchronizace pracovních dnů od .
    /// </summary>
    public static string Synchronizator_AutoFrom {
        get {
            return ResourceManager.GetString("Synchronizator_AutoFrom", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to  do .
    /// </summary>
    public static string Synchronizator_AutoTo {
        get {
            return ResourceManager.GetString("Synchronizator_AutoTo", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Spustit od.
    /// </summary>
    public static string Synchronizator_Manual_From {
        get {
            return ResourceManager.GetString("Synchronizator_Manual_From", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ruční spuštění synchronizátoru.
    /// </summary>
    public static string Synchronizator_Manual_Title {
        get {
            return ResourceManager.GetString("Synchronizator_Manual_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to  do .
    /// </summary>
    public static string Synchronizator_Manual_To {
        get {
            return ResourceManager.GetString("Synchronizator_Manual_To", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nastavení synchronizátoru.
    /// </summary>
    public static string Synchronizator_Title {
        get {
            return ResourceManager.GetString("Synchronizator_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Přiřadit fakturu.
    /// </summary>
    public static string TimeEntries_AddInvoice {
        get {
            return ResourceManager.GetString("TimeEntries_AddInvoice", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Schválit vybrané.
    /// </summary>
    public static string TimeEntries_ApproveSelected {
        get {
            return ResourceManager.GetString("TimeEntries_ApproveSelected", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Zamítnout vybrané.
    /// </summary>
    public static string TimeEntries_CancelSelected {
        get {
            return ResourceManager.GetString("TimeEntries_CancelSelected", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Rozsah konce měření.
    /// </summary>
    public static string TimeEntries_DateRange {
        get {
            return ResourceManager.GetString("TimeEntries_DateRange", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Smazat vybrané.
    /// </summary>
    public static string TimeEntries_DeleteSelected {
        get {
            return ResourceManager.GetString("TimeEntries_DeleteSelected", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Rozpadnout.
    /// </summary>
    public static string TimeEntries_Expand {
        get {
            return ResourceManager.GetString("TimeEntries_Expand", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Filtrovat dle: Klienta.
    /// </summary>
    public static string TimeEntries_Filter_ByClient {
        get {
            return ResourceManager.GetString("TimeEntries_Filter_ByClient", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Filtrovat dle: Stavu faktury.
    /// </summary>
    public static string TimeEntries_Filter_ByInvoiceState {
        get {
            return ResourceManager.GetString("TimeEntries_Filter_ByInvoiceState", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Filtrovat dle: Projektu.
    /// </summary>
    public static string TimeEntries_Filter_ByProject {
        get {
            return ResourceManager.GetString("TimeEntries_Filter_ByProject", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Filtrovat dle: Stavu záznamu.
    /// </summary>
    public static string TimeEntries_Filter_ByState {
        get {
            return ResourceManager.GetString("TimeEntries_Filter_ByState", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Filtrovat dle: Uživatele.
    /// </summary>
    public static string TimeEntries_Filter_ByUser {
        get {
            return ResourceManager.GetString("TimeEntries_Filter_ByUser", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Filtrovat.
    /// </summary>
    public static string TimeEntries_Filter_Run {
        get {
            return ResourceManager.GetString("TimeEntries_Filter_Run", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Zahrnout schválené záznamy.
    /// </summary>
    public static string TimeEntries_Modal_AddApprovedEntries {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_AddApprovedEntries", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Zahrnout zamítnuté záznamy.
    /// </summary>
    public static string TimeEntries_Modal_AddCanceledEntries {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_AddCanceledEntries", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Přiřazení faktury.
    /// </summary>
    public static string TimeEntries_Modal_AddingInvoice {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_AddingInvoice", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Zahrnout záznamy ke schválení.
    /// </summary>
    public static string TimeEntries_Modal_AddToApproveEntries {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_AddToApproveEntries", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to  schválených záznamů.
    /// </summary>
    public static string TimeEntries_Modal_ApprovedEntries {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_ApprovedEntries", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to  zamítnutých záznamů.
    /// </summary>
    public static string TimeEntries_Modal_CanceledEntries {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_CanceledEntries", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Od.
    /// </summary>
    public static string TimeEntries_Modal_ChangeStateDetail_From {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_ChangeStateDetail_From", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Změny stavů záznamu.
    /// </summary>
    public static string TimeEntries_Modal_ChangeStateDetail_Title {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_ChangeStateDetail_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Do.
    /// </summary>
    public static string TimeEntries_Modal_ChangeStateDetail_To {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_ChangeStateDetail_To", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Kdy.
    /// </summary>
    public static string TimeEntries_Modal_ChangeStateDetail_When {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_ChangeStateDetail_When", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Kdo.
    /// </summary>
    public static string TimeEntries_Modal_ChangeStateDetail_Who {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_ChangeStateDetail_Who", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Proč.
    /// </summary>
    public static string TimeEntries_Modal_ChangeStateDetail_Why {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_ChangeStateDetail_Why", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to  záznamů ke schválení.
    /// </summary>
    public static string TimeEntries_Modal_EntriesToApprove {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_EntriesToApprove", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Dokončit.
    /// </summary>
    public static string TimeEntries_Modal_Finish {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_Finish", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Faktura přiřazena k .
    /// </summary>
    public static string TimeEntries_Modal_InvoiceAddedTo {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_InvoiceAddedTo", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Číslo faktury.
    /// </summary>
    public static string TimeEntries_Modal_InvoiceNo {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_InvoiceNo", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to  změněné .
    /// </summary>
    public static string TimeEntries_Modal_Versions_Changed {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_Versions_Changed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Porovnání .
    /// </summary>
    public static string TimeEntries_Modal_Versions_Compare {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_Versions_Compare", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to verze záznamu s předchozí verzí.
    /// </summary>
    public static string TimeEntries_Modal_Versions_EntriesWithPrevious {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_Versions_EntriesWithPrevious", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to  nezměněné .
    /// </summary>
    public static string TimeEntries_Modal_Versions_NoChanged {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_Versions_NoChanged", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Verze záznamu.
    /// </summary>
    public static string TimeEntries_Modal_Versions_Title {
        get {
            return ResourceManager.GetString("TimeEntries_Modal_Versions_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Schváli záznam.
    /// </summary>
    public static string TimeEntries_New_ApproveEntry {
        get {
            return ResourceManager.GetString("TimeEntries_New_ApproveEntry", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Rozmezí od - do *.
    /// </summary>
    public static string TimeEntries_New_DateRange {
        get {
            return ResourceManager.GetString("TimeEntries_New_DateRange", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Popis *.
    /// </summary>
    public static string TimeEntries_New_Description {
        get {
            return ResourceManager.GetString("TimeEntries_New_Description", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Projekt *.
    /// </summary>
    public static string TimeEntries_New_ProjectName {
        get {
            return ResourceManager.GetString("TimeEntries_New_ProjectName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Název tasku.
    /// </summary>
    public static string TimeEntries_New_TaskName {
        get {
            return ResourceManager.GetString("TimeEntries_New_TaskName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Vytvoření záznamu.
    /// </summary>
    public static string TimeEntries_New_Title {
        get {
            return ResourceManager.GetString("TimeEntries_New_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Účet *.
    /// </summary>
    public static string TimeEntries_New_User {
        get {
            return ResourceManager.GetString("TimeEntries_New_User", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Celkem: .
    /// </summary>
    public static string TimeEntries_Summary {
        get {
            return ResourceManager.GetString("TimeEntries_Summary", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Celkem schválených: .
    /// </summary>
    public static string TimeEntries_SummaryApproves {
        get {
            return ResourceManager.GetString("TimeEntries_SummaryApproves", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Celkem zamítnutých: .
    /// </summary>
    public static string TimeEntries_SummaryBans {
        get {
            return ResourceManager.GetString("TimeEntries_SummaryBans", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Celkem ke schválení: .
    /// </summary>
    public static string TimeEntries_SummaryDrafts {
        get {
            return ResourceManager.GetString("TimeEntries_SummaryDrafts", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Přiřadit fakturu.
    /// </summary>
    public static string TimeEntries_TableHeader_Action_AddInvoice {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_Action_AddInvoice", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Schválit.
    /// </summary>
    public static string TimeEntries_TableHeader_Action_Approve {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_Action_Approve", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Zamítnout.
    /// </summary>
    public static string TimeEntries_TableHeader_Action_Cancel {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_Action_Cancel", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Smazat.
    /// </summary>
    public static string TimeEntries_TableHeader_Action_Delete {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_Action_Delete", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Akce.
    /// </summary>
    public static string TimeEntries_TableHeader_Actions {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_Actions", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Schválených hodin.
    /// </summary>
    public static string TimeEntries_TableHeader_ApprovedCount {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_ApprovedCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Zamítnutých hodin.
    /// </summary>
    public static string TimeEntries_TableHeader_CanceledCount {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_CanceledCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Datum změny.
    /// </summary>
    public static string TimeEntries_TableHeader_ChangeDate {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_ChangeDate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Popis.
    /// </summary>
    public static string TimeEntries_TableHeader_Description {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_Description", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Doba trvání.
    /// </summary>
    public static string TimeEntries_TableHeader_Duration {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_Duration", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Konec.
    /// </summary>
    public static string TimeEntries_TableHeader_EndTime {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_EndTime", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Od.
    /// </summary>
    public static string TimeEntries_TableHeader_From {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_From", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to ID v měřiči.
    /// </summary>
    public static string TimeEntries_TableHeader_IdInTimeTracker {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_IdInTimeTracker", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Čas importu.
    /// </summary>
    public static string TimeEntries_TableHeader_ImportedDate {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_ImportedDate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Číslo faktury.
    /// </summary>
    public static string TimeEntries_TableHeader_InvoiceNo {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_InvoiceNo", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Název projektu.
    /// </summary>
    public static string TimeEntries_TableHeader_ProjectName {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_ProjectName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Vybrat záznam.
    /// </summary>
    public static string TimeEntries_TableHeader_Select {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_Select", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Začátek.
    /// </summary>
    public static string TimeEntries_TableHeader_StartTime {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_StartTime", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Stav.
    /// </summary>
    public static string TimeEntries_TableHeader_StateName {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_StateName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Název tasku.
    /// </summary>
    public static string TimeEntries_TableHeader_TaskName {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_TaskName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Do.
    /// </summary>
    public static string TimeEntries_TableHeader_To {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_To", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Hodin ke schválení.
    /// </summary>
    public static string TimeEntries_TableHeader_ToAprroveCount {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_ToAprroveCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Celkový počet hodin.
    /// </summary>
    public static string TimeEntries_TableHeader_TotalCount {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_TotalCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Účet.
    /// </summary>
    public static string TimeEntries_TableHeader_UserName {
        get {
            return ResourceManager.GetString("TimeEntries_TableHeader_UserName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Další.
    /// </summary>
    public static string TimeEntries_TablePager_Next {
        get {
            return ResourceManager.GetString("TimeEntries_TablePager_Next", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Předchozí.
    /// </summary>
    public static string TimeEntries_TablePager_Previous {
        get {
            return ResourceManager.GetString("TimeEntries_TablePager_Previous", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Účty časovače.
    /// </summary>
    public static string TimeEntries_Tracker_Accounts {
        get {
            return ResourceManager.GetString("TimeEntries_Tracker_Accounts", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Klíč.
    /// </summary>
    public static string TimeEntries_Tracker_Key {
        get {
            return ResourceManager.GetString("TimeEntries_Tracker_Key", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Název časovače.
    /// </summary>
    public static string TimeEntries_Tracker_Name {
        get {
            return ResourceManager.GetString("TimeEntries_Tracker_Name", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Přidání/aktualizace účtu časovače.
    /// </summary>
    public static string TimeEntries_Tracker_Title {
        get {
            return ResourceManager.GetString("TimeEntries_Tracker_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Měřič.
    /// </summary>
    public static string TimeEntries_Tracker_TrackerName {
        get {
            return ResourceManager.GetString("TimeEntries_Tracker_TrackerName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Došlo k chybě při ověřování přístupu Vašeho účtu k aplikaci. Vyzkoušejte funkci odhlášení nebo kontaktujte administrátora..
    /// </summary>
    public static string Unauthorized_Reason {
        get {
            return ResourceManager.GetString("Unauthorized_Reason", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Neautorizovaný přístup.
    /// </summary>
    public static string Unauthorized_Title {
        get {
            return ResourceManager.GetString("Unauthorized_Title", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Přidat.
    /// </summary>
    public static string Workspaces_Add {
        get {
            return ResourceManager.GetString("Workspaces_Add", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Již přidán.
    /// </summary>
    public static string Workspaces_Added {
        get {
            return ResourceManager.GetString("Workspaces_Added", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to API token Toggl účtu.
    /// </summary>
    public static string Workspaces_ApiTogglToken {
        get {
            return ResourceManager.GetString("Workspaces_ApiTogglToken", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Načíst.
    /// </summary>
    public static string Workspaces_Load {
        get {
            return ResourceManager.GetString("Workspaces_Load", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Načtené workspaces.
    /// </summary>
    public static string Workspaces_LoadedTitle {
        get {
            return ResourceManager.GetString("Workspaces_LoadedTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Načíst z účtu.
    /// </summary>
    public static string Workspaces_LoadTitle {
        get {
            return ResourceManager.GetString("Workspaces_LoadTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Název workspace.
    /// </summary>
    public static string Workspaces_Name {
        get {
            return ResourceManager.GetString("Workspaces_Name", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Uložené workspaces.
    /// </summary>
    public static string Workspaces_Title {
        get {
            return ResourceManager.GetString("Workspaces_Title", resourceCulture);
        }
    }
}
