//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itixo.Timesheets.Shared.Resources; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Texts {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Texts() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itixo.Timesheets.Shared.Resources.Texts", typeof(Texts).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nepodařilo se načíst údaje. Kontaktujte administrátora..
    /// </summary>
    public static string Account_Failed_To_Load_Identity_Info {
        get {
            return ResourceManager.GetString("Account_Failed_To_Load_Identity_Info", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Účet úspěšně přidán..
    /// </summary>
    public static string AddingAccess_SuccessMessage_Adding_Was_Successful {
        get {
            return ResourceManager.GetString("AddingAccess_SuccessMessage_Adding_Was_Successful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Workspace přidán..
    /// </summary>
    public static string AddWorkspace_SuccessMessage_Workspace_Added {
        get {
            return ResourceManager.GetString("AddWorkspace_SuccessMessage_Workspace_Added", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Configuration has been updated with value {0}.
    /// </summary>
    public static string ApiReponse_ConfigurationUpdated_Configuration_Has_Been_Updated_With_Value {
        get {
            return ResourceManager.GetString("ApiReponse_ConfigurationUpdated_Configuration_Has_Been_Updated_With_Value", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Record already exists.
    /// </summary>
    public static string ApiResponse_ConfigurationNotChanged_Record_Already_Exists {
        get {
            return ResourceManager.GetString("ApiResponse_ConfigurationNotChanged_Record_Already_Exists", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Configuration with value {0} has been added.
    /// </summary>
    public static string ApiResponse_InsertedConfiguration_Configuration_With_Value_Has_Been_Added {
        get {
            return ResourceManager.GetString("ApiResponse_InsertedConfiguration_Configuration_With_Value_Has_Been_Added", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to ExternalId was not found.
    /// </summary>
    public static string ApiUserRepository_NotFound_ExternalId_Was_Not_Found {
        get {
            return ResourceManager.GetString("ApiUserRepository_NotFound_ExternalId_Was_Not_Found", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to ExternalId was not found in database.
    /// </summary>
    public static string ApiUserRepository_NotFoundMessage_ExternalId_Was_Not_Found_In_Database {
        get {
            return ResourceManager.GetString("ApiUserRepository_NotFoundMessage_ExternalId_Was_Not_Found_In_Database", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznam se nepodařilo schválit..
    /// </summary>
    public static string ApproveTimeEntryDraft_ErrorMessage_Record_Cant_Be_Approved {
        get {
            return ResourceManager.GetString("ApproveTimeEntryDraft_ErrorMessage_Record_Cant_Be_Approved", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznam schválen..
    /// </summary>
    public static string ApproveTimeEntryDraft_SuccessMessage_Record_Was_Approved {
        get {
            return ResourceManager.GetString("ApproveTimeEntryDraft_SuccessMessage_Record_Was_Approved", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Not allowed method.
    /// </summary>
    public static string BadRequest_Message_Not_Allowed_Method {
        get {
            return ResourceManager.GetString("BadRequest_Message_Not_Allowed_Method", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznam zamítnut..
    /// </summary>
    public static string BanTimeEntryDraft_SuccessMessage_Record_Was_Banned {
        get {
            return ResourceManager.GetString("BanTimeEntryDraft_SuccessMessage_Record_Was_Banned", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznamy se nepodařilo schválit..
    /// </summary>
    public static string BulkApproveTimeEntryDrafts_ErrorMessage_Records_Approvement_Was_Not_Successful {
        get {
            return ResourceManager.GetString("BulkApproveTimeEntryDrafts_ErrorMessage_Records_Approvement_Was_Not_Successful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznamy schváleny a uloženy do Záznamů..
    /// </summary>
    public static string BulkApproveTimeEntryDrafts_SuccessMessage_Records_Approvement_Was_Successful {
        get {
            return ResourceManager.GetString("BulkApproveTimeEntryDrafts_SuccessMessage_Records_Approvement_Was_Successful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nejsou vybrané záznamy..
    /// </summary>
    public static string BulkBanTimeEntryDrafts_ErrorMessage_Records_Ban_Was_Not_Successful {
        get {
            return ResourceManager.GetString("BulkBanTimeEntryDrafts_ErrorMessage_Records_Ban_Was_Not_Successful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznamy byly zamítnuty..
    /// </summary>
    public static string BulkBanTimeEntryDrafts_SuccessMessage_Records_Ban_Was_Successful {
        get {
            return ResourceManager.GetString("BulkBanTimeEntryDrafts_SuccessMessage_Records_Ban_Was_Successful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nebyly vybrány žádné záznamy.
    /// </summary>
    public static string BulkDeleteTimeEntries_ErrorMessage_Records_Not_Selected {
        get {
            return ResourceManager.GetString("BulkDeleteTimeEntries_ErrorMessage_Records_Not_Selected", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznamy úspěšně smazány.
    /// </summary>
    public static string BulkDeleteTimeEntryDrafts_SuccessMessage_Records_Delete_Was_Successful {
        get {
            return ResourceManager.GetString("BulkDeleteTimeEntryDrafts_SuccessMessage_Records_Delete_Was_Successful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Invalid form data..
    /// </summary>
    public static string CommonAPiValidation_InvalidData_Invalid_form_data {
        get {
            return ResourceManager.GetString("CommonAPiValidation_InvalidData_Invalid_form_data", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Smazání účtu se nepodařilo..
    /// </summary>
    public static string DeleteAccount_ErrorMessage_Delete_Was_Not_Successful {
        get {
            return ResourceManager.GetString("DeleteAccount_ErrorMessage_Delete_Was_Not_Successful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Účet uložen..
    /// </summary>
    public static string DeleteAccount_SuccessMessage_Delete_Was_Successful {
        get {
            return ResourceManager.GetString("DeleteAccount_SuccessMessage_Delete_Was_Successful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Záznam úspěšně smazán.
    /// </summary>
    public static string DeleteTimeEntryDraft_SuccessMessage_Record_Was_Deleted {
        get {
            return ResourceManager.GetString("DeleteTimeEntryDraft_SuccessMessage_Record_Was_Deleted", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Project with Id {0} was not found.
    /// </summary>
    public static string ProjectRepository_RemoveProjectAsync_Project_With_Id_Was_Not_Found {
        get {
            return ResourceManager.GetString("ProjectRepository_RemoveProjectAsync_Project_With_Id_Was_Not_Found", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Workspaces odebrán..
    /// </summary>
    public static string RemvoeWorkspaces_Success_Message_Workspace_Removed {
        get {
            return ResourceManager.GetString("RemvoeWorkspaces_Success_Message_Workspace_Removed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Record was created.
    /// </summary>
    public static string Repository_AddMessage_Record_Was_Created {
        get {
            return ResourceManager.GetString("Repository_AddMessage_Record_Was_Created", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Record was successfully removed.
    /// </summary>
    public static string Repository_RemoveMessage_Record_Was_Successfully_Removed {
        get {
            return ResourceManager.GetString("Repository_RemoveMessage_Record_Was_Successfully_Removed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Record was updated.
    /// </summary>
    public static string Repository_UpdateMessage_Record_Was_Updated {
        get {
            return ResourceManager.GetString("Repository_UpdateMessage_Record_Was_Updated", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Synchronizace byla dokončena..
    /// </summary>
    public static string Synchronization_SuccessMessage_Synchronization_Done {
        get {
            return ResourceManager.GetString("Synchronization_SuccessMessage_Synchronization_Done", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Success.
    /// </summary>
    public static string SynchronizationFunction_Run_Success {
        get {
            return ResourceManager.GetString("SynchronizationFunction_Run_Success", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Workspace Id {0} not found.
    /// </summary>
    public static string WorkspaceRepository_NotFoundWorkspace_Workspace_Id_Not_Found {
        get {
            return ResourceManager.GetString("WorkspaceRepository_NotFoundWorkspace_Workspace_Id_Not_Found", resourceCulture);
        }
    }
}
