//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itixo.Timesheets.Shared.Resources; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Validations {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Validations() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itixo.Timesheets.Shared.Resources.Validations", typeof(Validations).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Klíč je povinný údaj..
    /// </summary>
    public static string AccountWorkspaces_ValidationMessage_ExternalId_Cant_Be_Empty {
        get {
            return ResourceManager.GetString("AccountWorkspaces_ValidationMessage_ExternalId_Cant_Be_Empty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Přidání účtu selhalo..
    /// </summary>
    public static string AddingAccount_ValidationMessage_Adding_Was_Not_Successful {
        get {
            return ResourceManager.GetString("AddingAccount_ValidationMessage_Adding_Was_Not_Successful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to ID pro zamítnutí musí být větší než 0..
    /// </summary>
    public static string BanTimeEntryDraftValidator_ValidationMessage_Id_Greater_Than_Zero {
        get {
            return ResourceManager.GetString("BanTimeEntryDraftValidator_ValidationMessage_Id_Greater_Than_Zero", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Hodnota musí být větší než nula..
    /// </summary>
    public static string Common_IntegerValidation_Value_More_Than_Zero {
        get {
            return ResourceManager.GetString("Common_IntegerValidation_Value_More_Than_Zero", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Klíč konfigurace musí být unikátní..
    /// </summary>
    public static string ConfigurationKeyUniquenessValidator_Handle_Configuration_key_Unique {
        get {
            return ResourceManager.GetString("ConfigurationKeyUniquenessValidator_Handle_Configuration_key_Unique", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Klíč konfigurace je povinný údaj..
    /// </summary>
    public static string ConfigurationValidator_Configuration__Key_Cannot_Be_Empty {
        get {
            return ResourceManager.GetString("ConfigurationValidator_Configuration__Key_Cannot_Be_Empty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Hodnota Konfigurace je povinný údaj..
    /// </summary>
    public static string ConfigurationValidator_Configuration_Value_Cannot_Be_Empty {
        get {
            return ResourceManager.GetString("ConfigurationValidator_Configuration_Value_Cannot_Be_Empty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Konfigurace neexistuje..
    /// </summary>
    public static string ConfigurationValidator_Configuration_With_Id_Does_Not_Exist {
        get {
            return ResourceManager.GetString("ConfigurationValidator_Configuration_With_Id_Does_Not_Exist", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to TimeEntryId musí být větší než 0..
    /// </summary>
    public static string GetTimeEntryVersionsQueryValidator_GetTimeEntryVersionsQueryValidator_TimeEntryId_must_be_greater_than_zero {
        get {
            return ResourceManager.GetString("GetTimeEntryVersionsQueryValidator_GetTimeEntryVersionsQueryValidator_TimeEntryId" +
                    "_must_be_greater_than_zero", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Date cannot be default.
    /// </summary>
    public static string LogSyncCommandValidator_LogSyncCommandValidator_Date_cannot_be_default {
        get {
            return ResourceManager.GetString("LogSyncCommandValidator_LogSyncCommandValidator_Date_cannot_be_default", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to When Kind is 0 Then StartDate must be filled Or When Kind is 1 Then StoppedDate must be filled.
    /// </summary>
    public static string LogSyncCommandValidator_LogSyncCommandValidator_When_Kind_is_0_Then_StartDate_must_be_filled_Or_When_Kind_is_1_Then_StoppedDate_must_be_filled {
        get {
            return ResourceManager.GetString("LogSyncCommandValidator_LogSyncCommandValidator_When_Kind_is_0_Then_StartDate_mus" +
                    "t_be_filled_Or_When_Kind_is_1_Then_StoppedDate_must_be_filled", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Během přiřazování faktury došlo k změnám v záznamech. Aktualizujte stránku a opakujte..
    /// </summary>
    public static string ReportsInvoiceAssignment_ValidationMessage_Data_Was_Changed {
        get {
            return ResourceManager.GetString("ReportsInvoiceAssignment_ValidationMessage_Data_Was_Changed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to TimeEntryId must be greater than 0..
    /// </summary>
    public static string StateChangesByTimeEntryIdQueryValidator_StateChangesByTimeEntryIdQueryValidator_TimeEntryId_must_be_greater_than_0_ {
        get {
            return ResourceManager.GetString("StateChangesByTimeEntryIdQueryValidator_StateChangesByTimeEntryIdQueryValidator_T" +
                    "imeEntryId_must_be_greater_than_0_", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Hodnota &apos;Do&apos; musí být větší nebo rovna hodnotě &apos;Od&apos;.
    /// </summary>
    public static string SyncBusinessDays_ValidationMessage_Start_Must_Be_Greater_Tan_Stop {
        get {
            return ResourceManager.GetString("SyncBusinessDays_ValidationMessage_Start_Must_Be_Greater_Tan_Stop", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Datum &apos;Od&apos; musí být starší než datum &apos;Do&apos;..
    /// </summary>
    public static string TriggerSynchronization_ValidationMesssage_StartDate_Must_Be_Greater_Than_EndDate {
        get {
            return ResourceManager.GetString("TriggerSynchronization_ValidationMesssage_StartDate_Must_Be_Greater_Than_EndDate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Email nemůže být prázdný..
    /// </summary>
    public static string UpdateCurrentIdentityInfoValidator_UpdateCurrentIdentityInfoValidator_Email_cant_be_empty {
        get {
            return ResourceManager.GetString("UpdateCurrentIdentityInfoValidator_UpdateCurrentIdentityInfoValidator_Email_cant_" +
                    "be_empty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Klíč je povinný údaj..
    /// </summary>
    public static string UserDetailModel_ValidationMessage_ExternalId_is_Required {
        get {
            return ResourceManager.GetString("UserDetailModel_ValidationMessage_ExternalId_is_Required", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Název účtu je povinný údaj..
    /// </summary>
    public static string UserDetailModel_ValidationMessage_Name_Of_Account_Is_Required {
        get {
            return ResourceManager.GetString("UserDetailModel_ValidationMessage_Name_Of_Account_Is_Required", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Přiřaďte účtu měřič..
    /// </summary>
    public static string UserDetailModel_ValidationMessage_TimeTrackerId_is_Required {
        get {
            return ResourceManager.GetString("UserDetailModel_ValidationMessage_TimeTrackerId_is_Required", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Pole klíč je povinný údaj..
    /// </summary>
    public static string UserForm_ValidationMessage_Api_Token_Cant_Be_Empty {
        get {
            return ResourceManager.GetString("UserForm_ValidationMessage_Api_Token_Cant_Be_Empty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Název účtu je povinný údaj..
    /// </summary>
    public static string UserForm_ValidationMessage_Username_Cant_Be_Empty {
        get {
            return ResourceManager.GetString("UserForm_ValidationMessage_Username_Cant_Be_Empty", resourceCulture);
        }
    }
}
